apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-apache-1 # Unique name for each Apache deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: apache
          image: httpd:latest # Apache image
          ports:
            - containerPort: 80

---
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: frontend-nginx-1 # Unique name for each Nginx deployment
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: frontend
#   template:
#     metadata:
#       labels:
#         app: frontend
#     spec:
#       containers:
#         - name: nginx
#           image: nginx:latest # Nginx image
#           ports:
#             - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend # This matches both Apache and Nginx pods
  ports:
    - protocol: TCP
      port: 80 # External port exposed by the service
      targetPort: 80 # Port on the pods that the service forwards traffic to
  type: LoadBalancer # This makes the service a LoadBalancer type

