replicaCount: 1

image:
  repository: nginx
  tag: stable
  pullPolicy: IfNotPresent

service:
  name: nginx
  type: ClusterIP
  port: 80 # This line defines the port

resources: {}
demo-subchart:
  customValue: "hello from nginx"
global:
  defaultStorageClass: "my-custom-storageclass-nick"

postgresql:
  enabled: true
