apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi # Requested storage size (EBS volumes in AWS are at least 1Gi)
  storageClassName: ebs-storage # Ensure it matches the StorageClass name
